@startuml
start
:Начало;
if (Фронтенд готов) then (yes)
  :Редактирование кода;
else (no)
  :Ожидание;
endif
if (Код сохранен) then (yes)
  :Отправка кода на бэкенд;
else (no)
  :Ожидание;
endif
if (Бэкенд готов) then (yes)
  :Выполнение кода;
else (no)
  :Ожидание;
endif
:Отправка результата на фронтенд;
stop
@enduml
