@startuml
[*] --> Фронтенд_Ожидание

state Фронтенд_Ожидание {
    Фронтенд_Ожидание --> Фронтенд_Редактирование : Начать редактирование кода
}

state Фронтенд_Редактирование {
    Фронтенд_Редактирование --> Фронтенд_Ожидание : Сохранить код
}

[*] --> Бэкенд_Ожидание

state Бэкенд_Ожидание {
    Бэкенд_Ожидание --> Бэкенд_Выполнение : Получить код на выполнение
}

state Бэкенд_Выполнение {
    Бэкенд_Выполнение --> Бэкенд_Ожидание : Завершить выполнение
}

Фронтенд_Редактирование --> Бэкенд_Ожидание : Отправить код
Бэкенд_Выполнение --> Фронтенд_Ожидание : Отправить результат

Фронтенд_Ожидание: Фронтенд ожидает ввода кода
Фронтенд_Редактирование: Фронтенд редактирует код
Бэкенд_Ожидание: Бэкенд ожидает получения кода
Бэкенд_Выполнение: Бэкенд выполняет код

@enduml
